PHPAuth/PHPAuth

auth.class.php

If you are behind a reverse proxy (as android chrome is by default) the REMOTE_ADDR will always be the IP of the proxy server and the user IP will be provided in an HTTP header (X-Forwarded-For).

Fix for reverse proxy server lookup

---

auth.class.php

$addrequest= missed on line 239
if ($addRequest = $this->addRequest($query->fetch(PDO::FETCH_ASSOC)['id'], $email, "reset")['error'] == 1)
but due to the way the line of the code is writen, this won't work on my server.
fixed it by defining $addRequest separatly

fixed missing $addRequest definition

---

auth.class.php

'key_incorrect' and 'key_expired' are not defined in language files.
fixed key name in function call and renamed key name in language files

fixed missing and bad language line target in getRequest()

---

auth.class.php

Incorrect config parameter when creating the password restore email - "site_activation_page" instead of "site_password_reset_page".

Password restore email fix

---

config.class.php

`config_table` defined
`phpauth_config_table` used

fix to the last fix - bad variable name

---

auth.class.php

if `$password` don't match `$repeatpassword`, other verifications are useless

Fixed password check conditions order

---

auth.class.php

If you don't specify any additional params while calling PHPAuth->register the addUser() function adds a comma after the password resulting in a invalid query
<a href='https://www.codereviewhub.com/PHPAuth/PHPAuth/pull/95?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/PHPAuth/PHPAuth/pull/95'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Additional registration params empty -> invalid query

---

auth.class.php

The query to get attempts in function isBlocked() asks for the 'count' column that has been removed in #99 and the  following rowCount returns always zero. Removing the count column fixes the error.

Advanced attack mitigation attempts are always 0

---

auth.class.php

The query in deleteAttempts asks for the count column that doesn't exists and return 0 rows.
Attempts are never removed. Removing the 'count' column from the query fixes the problem.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/PHPAuth/PHPAuth/pull/105%23issuecomment-140238304%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/105%23issuecomment-140239913%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/105%23issuecomment-140248767%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/105%23issuecomment-140238304%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22No%20problem%2C%20I%20made%20a%20mistake%20too%2C%20please%20refuse%20this%20pull%2C%20the%20%2 …

Advanced attack mitigation doesn't delete expired attempts

---

auth.class.php

Previous logic resulted in $setParams as empty string when calling register method without additional params. This throws error on PHP server depending on settings.
Corrected by assigning empty string conditionally.
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/Conver%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6231022%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/109%23issuecomment-140903135%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-09-16T21%3A45%3A26Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6231022% …

bugfix PHP error undefined variable in register class.

---

auth.class.php

Better use select count(*) instead of $query->rowCount() when not using others fetched params.
<a href='https://www.codereviewhub.com/PHPAuth/PHPAuth/pull/111?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/PHPAuth/PHPAuth/pull/111'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Inefficient count system

---

auth.class.php

The $query variable in the while loop was overwritten inside the loop, causing this error on the next iteration
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/Conver%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6231022%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/112%23issuecomment-141156286%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-09-17T17%3A18%3A03Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6231022%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Conver%22%7D%7D%5D%2C%20%22title%22%3A%20%22 …

 Uncaught exception 'PDOException' if deleteAttempts

---

auth.class.php

Resolves issue where testing if !$mail->send() would generate empty email into space when email suppressed.
<a href='https://www.codereviewhub.com/PHPAuth/PHPAuth/pull/114?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/PHPAuth/PHPAuth/pull/114'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Bugfix suggested by JacquesLoubser, avoids sending empty email

---

auth.class.php

Password is not returned for security reason.
The public interface has not been changed, the old getUser() used internally has been transfofrmed to private
<a href='https://www.codereviewhub.com/PHPAuth/PHPAuth/pull/117?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/PHPAuth/PHPAuth/pull/117'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

PHPAuth\Auth->getUser() returns all custom user data 

---

auth.class.php
database.sql
languages/de_DE.php
languages/en_GB.php
languages/fr_FR.php
languages/it_IT.php
languages/ru_RU.php

This time completely hard reset my local master first per JacquesLoubser.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/PHPAuth/PHPAuth/pull/121%23issuecomment-142060232%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/121%23issuecomment-142061793%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/121%23issuecomment-142063214%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/121%23issuecomment-142060232%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22What%20is%20your%20PR%20meant%20to%20do%3F%5Cr%5Cn%5Cr%5CnI%20dont%20really%20see%20anything%20beside%20adding%20%60%24this-%3Elang%5B%27reset_requested%27%5D%3D%24this-%3Elang%5B%27reset_requested_emailm …

Reimplemented language messages for suppressed emails

---

auth.class.php

During the reset process if the new password matches the old password the request is cancelled from the db and the key became invalid and you have to request a new one.
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/Conver%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6231022%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/127%23issuecomment-145509483%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-10-05T12%3A16%3A51Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6231022%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A …

reset key invalid if new password matches ol password

---

auth.class.php

the fix for account creation without mail, but activation key created
now if $sendmail is set to FALSE, addRequest is ignored  and the account is activated.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/PHPAuth/PHPAuth/pull/124%23issuecomment-143018447%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/124%23issuecomment-143146500%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/124%23issuecomment-143018447%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Wouldn%27t%20it%20be%20easier%20just%20adding%20it%20to%20the%20config%20table%2C%20if%20the%20user%20wish%20to%20use%20it%20or%20not%2C%20instead%20of%20having%20to%20alter%20the%20code%3F%22%2C%20%22cr …

account creation  : activation key problem fix

---

README.md
composer.json

Added basic support for composer with PSR-4 autoloader and documentation.
<a href='https://www.codereviewhub.com/PHPAuth/PHPAuth/pull/133?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/PHPAuth/PHPAuth/pull/133'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Added composer compatability

---

languages/nl_BE.php
languages/nl_NL.php

In dutch we tend to say 'Wachtwoord' instead of 'Paswoord'. Also, addres and address are both incorrect in both languages

Minor spelling mistakes

---

Auth.php

I'm unable to validate an activate key's expire date because the row is always fetched twice, causing $row to be false. I see no reason to fetch again. It will also fetch using the default PDO fetchMode. I'm wondering how getRequest can be returning the correct id and uid without this change.

Stop fetching request twice

---

Auth.php

1. On the PostgreSQL database statement `INSERT INTO users VALUES ()` fails with the following message:
```
ERROR:  syntax error at or near ")"
LINE 1: INSERT INTO auth_users VALUES ()
^
```
2. `lastInsertId()` returns `false` for PostgreSQL. Sequence name should be passed.
see: http://stackoverflow.com/questions/10492566/lastinsertid-does-not-work-in-postgresql

Fix Auth::addUser() for postgresql db

---

database_mssql.sql

Added script to add tables/default data to MSSQL/SQLServer databases. Set Identity to certain columns so creating records then using lastInsertID() doesn't break. May need to modify certain columns settings so doing lastInsertID() by name works properly.
PHPAuth should support SQLServer and MSSQL since there are PDO libraries for it. I've run into zero issues that weren't solved by changing settings/configurations in the database server itself, with PHPAuth working out of box once configuration was done. If anyone using MSSQL/SQLServer needs help they can pm me.

Added MSSQL/SQLServer table creation script

---

Auth.php

I noticed that use of PHPMailer namespace is incorrect when I wanted to use register() method with $sendmail set to true.
`PHP Fatal error:  Class 'PHPMailer\PHPMailer\PHPMailer' not found in /PHPAuth/Auth.php on line 786`

Fix phpmailer namespace error

---

Auth.php

Not all of the clients provides HTTP_USER_AGENT. PHPAuth crashed if was missing.

HTTP_USER_AGENT is optional

---

Auth.php

Good afternoon,
This PR makes changing a user's password possible without the current password parameter being mandatory. I needed this because administrators of my application needed to be able to do a forced password reset on a specific user, without having to send the user a password recovery email.

Make current password parameter mandatory for changePassword

---

Auth.php

Rehash the users password if the currently saved hash does not meet the current requirements set by parameter `bcrypt_cost`.

Verify password with rehash at login.

---

Auth.php

First of all, strange that no one can report Issues. Please enable it.
I'm trying to setup PHPAuth using Composer, but I receive the following error out-of-the-box:
`PHP Fatal error: Uncaught Error: Class 'PHPMailer\PHPMailer\PHPMailer' not found in C:\Users\X\vendor\phpauth\phpauth\Auth.php:794`
So I checked out Auth.php and it seems that Composer changes `use PHPMailer;` to `use PHPMailer\PHPMailer\PHPMailer;` which is probably incorrect. So I reverted this change back to `use PHPMailer;` and the issue disappeared.
I'm not an expert in Composer, so there is probably an issue, or am I missing something?
Thanks

Fix fatal error when using Composer

---

Config.php

Between version 1.1.1 and 1.1.2 the capability to pass the table name for the PHPAuth config to constructor has been moved in the parameter order, causing a breaking error for anyone who used this functionality.
While the fix is mostly trivial it would be good to maintain backwards compatibility, especially in patch versions.

Changed parameter order of config to maintain backwards compatability

---

database_defs/database_informix.sql
database_defs/database_mssql.sql
database_defs/database_mysql.sql
database_defs/database_pgsql.sql

If you choose to use the sql translation source it doesn't work. The phpauth_config contains value "phpauth_translations" when in fact it should be "phpauth_translation_dictionary".

Updated config with the correct translation table name

---

Auth.php
languages/sl_SI.php
tests/AuthTest.php

Cleans up some loose ends from #327, and improves test coverage.
- Adds logoutAll method that deletes all sessions for uid
- Changes behavior of deleteExistingSessions to return true if at least one session was deleted (instead of exactly 1)
- Expiring session deletes only that session
- Rotating session hash deletes/replaces only that session
- Adds tests for all of the new functionality, as well as tests for the existing code in checkSession that handles expiring sessions and IP mismatch.
- Fixes a bug in the unit tests where testLogout depends on testChangeEmail, not just testCheckSession.

Handle expired sessions with concurrent sessions, logoutAll

---

languages/en_GB.php

Translation for account_not_found
Auth.php
Method public function login  
...
if (!$uid) {
$this->addAttempt();
$return['message'] = $this->__lang("account_not_found");
return $return;
}

Missing translation for  account_not_found

---

Auth.php

This PR adds a new public method `cron()`, aswell as three private methods:
* `deleteExpiredAttempts()`
* `deleteExpiredRequests()`
* `deleteExpiredSessions()`
The idea is to use the public method to frequently cleanup the database, here's an example callable script:
```php
<?php
require_once("vendor/autoload.php");
$dbh = new PDO("mysql:host=localhost;dbname=phpauth_db", "username", "password");
$config = new PHPAuth\Config($dbh);
$auth   = new PHPAuth\Auth($dbh, $config);
$auth->cron();
```

Fix #379 - Add cron method to cleanup expired sessions, requests and attempts

---

Auth.php
Config.php

Replace all "SHOW TABLES LIKE ..." Statements to "SELECT * FROM ...", surrounded by try catch blocks to create compatibility with databases, that don´t support "SHOW TABLES LIKE ..."

PostgreSQL Compatability

---

Auth.php

I have removed the column in Select. This is the only place where a username is used.

BUGFIX: username column not exist #390

---

Auth.php
database_defs/database_informix.sql
database_defs/database_mssql.sql
database_defs/database_mysql.sql
database_defs/database_pgsql.sql

i have users who use an app on smartphone; but a problem is, that the ip of the phone changes very often (using different wifi's, mobile data and so on).
i also have to call checkSession manually, because the isLogged function uses the getCurrentSessionHash function, which reads a cookie. we should also improve having a choice **to choose from where the hash get's read from**, not only cookie.
the device_id is a v4 uuid - **i added it in the mysql def ONLY**.
now i want to hear your opinion - maybe there is improvement on this?

use device_id instead of ip for authentication

---

Auth.php
database_defs/database_informix.sql
database_defs/database_mssql.sql
database_defs/database_mysql.sql
database_defs/database_pgsql.sql

I figured out that the timestamp - at which the current request resets/expires - is in the message-text when trying to create another request.
Because we germans have a different order of year, month and date, i wrote a function which returns the formatted, readable timestamp. 
I think we will need this function in future.

formatting of printed timestamps

---

Auth.php
Config.php
README.md
composer.json
database_defs/database_informix.sql
database_defs/database_mssql.sql
database_defs/database_mysql.sql
database_defs/database_pgsql.sql

`days_for_automatic_password_expiration` number of default days before password expiration, if set  to 0 password globally doesn't expire.
`phpauth_params` table to storage json structure of field params, if empty use old behavior requiring  modifying the table to accept params. 
`default_jwt_iss`   the default issuer claim for jwt token
`default_jwt_aud`  the default audience claim for jwt token
`expiration` datetime: date after which the password is considered as expired.
`days2expire` int(3):  per user configuration, when used is created by default uses configuration option of `days_for_automatic_password_expiration` if set to 0, pass
word does't expire. This is a per user configuration.
`params` JSON: Storage of the fields described by `phpauth_params`, as a json_object.
`status` enum …

Automatic exporation for password, JSON storage and JWT Token

---

composer.json

zxcvbn-php bump version from 0.4 to 1.0. PHP support 7.0

zxcvbn bump version

---

Config.php

From issue https://github.com/PHPAuth/PHPAuth/issues/484
> With PHP 8.0.1 (but not PHP 7.4.14), Config.php doesn't compile because the return type specified for the __set() method, declared as "bool", so offends the compiler that it throws a fatal error with this message:
> 
> PHP Fatal error: PHPAuth\Config::__set(): Return type must be void when declared in /home/rose/public_html/phpauth/vendor/phpauth/phpauth/Config.php on line 253
I have removed the return value. With or without will make no difference.

CHANGE: Remove return type from __set() method #484

---

database_defs/database_pgsql.sql

The `character varying` data type can also be written as `varchar` but there's this one line that's written `varchar varying` that stopped the db initialization for me. This commit just changes it to the long form that is used throughout the rest of the file.
_PS: I still ended up having to switch to MySQL anyways though because apparently the backtick quoting used in queries has a totally different meaning in PostgreSQL... which makes it incompatible unless you go through and replace all the backticks used in this library._

Fix syntax in postgres dump file

---

README.md

The `__construct` function for the class in Config.php orders the input variables as "PDO, Source, Type ..."
```php
public function __construct(PDO $dbh, $config_source = null, string $config_type = '', string $config_site_language = '')
{
// code...
}
```
... but the the README info says that the "Source" and "Type" inputs are flipped. Took me a bit to figure out the problem when  I decided to use a custom table name.
I only changed the README to match since changing the code might be more problematic, not sure if there's other documentation that would need to be changed.

Correct documentation on Config class' construct variables

---

Auth.php

i use proxies in front of my websers and the function getIp() returned a list of ip addresses instead of a single one. this caused a PDO exception (truncated data).
It now returns the first ip address of the list.

fix ip address

---

Auth.php

Running the current version of PHPAuth on PHP 8.1.2 results in a notice from the framework stating that null values can no longer be supplied to the second parameter of setcookie. This causes the framework to return a 500 error. Making this small change allows the framework in its current state to operate on PHP 8.1
https://php.watch/versions/8.1/internal-func-non-nullable-null-deprecation
https://www.php.net/manual/en/function.setcookie.php

Resolve null setcookie value for PHP 8+

---

sources/Auth.php

not found for `verify.no_pair_user_and_password`
see:
https://github.com/PHPAuth/PHPAuth/blob/df1c90f60987cb9e752d085c7ddd1a3ad56129e1/sources/Helpers.php#L182-L205

fix : not found for `verify.no_pair_user_and_password`

---

languages/en_GB.php
sources/Helpers.php

"Are" for plural. "Is" for singular.

Fix typo (English).

---

files/import.php
sources/Auth.php

* Fixes some typos (`sources/Auth.php` and `files/import.php`).
* Changes one `array($foo);` to `[$foo];` (`files/import.php`).
* Improves type hints and phpdocs (`sources/Auth.php` and `files/import.php`).
There are other files where type hints and phpdocs could be improved, but this pull request just affects only two files, to make it easier to review the changes, and to avoid potential merge conflicts (if maintainers/contributors are working on changes for other files at the same time, more files changed in a single pull request could increase the risk of merge conflicts because of changes from different people to the same files).
Anyway, I hope this is helpful. :-)

Typos, type hints, phpdocs.
