languages/en.php

replaced activekey.. by activationkey... to match key name with $type variable in getRequest() function

fixed wrong key in getRequest() function

---

languages/fr.php

renamed 'activekey' to 'activationkey...' to match $type var in getRequest() function

fixed bad key definition for getRequest() function

---

languages/en.php

added missing caracters in email messages + removed unecessary linebreak for html format

fixed missing wildcards

---

languages/fr.php

added missing caracters in email messages + removed unecessary linebreak for html format

fixed missing wildcard

---

languages/de.php

I've translated to German informal.

Translated to German

---

auth.class.php

Added ability to add additional profile fields in the registration.

---

config.class.php

may be used in webapps with a lot of tables

hardcoded link to config table replaced by private config value

---

database.sql

Little fix: config table declaration will BEFORE all other declarations

database.sql fix : config table declaration will BEFORE others

---

README.md
auth.class.php
config.class.php
files/password.php

+ namespace for `auth.class.php` added
+ namespace for `config.class.php` added
+ fixed README.md
+ fixed PHPDocs

Namespace PHPAuth added.

---

auth.class.php

<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/Conver%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6231022%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/97%23issuecomment-139711300%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-09-12T04%3A14%3A44Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6231022%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Conver%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/PHPAuth/PHPAuth/pull/97%23issueco …

fixed PHPDocs, added two functions, changed visibility of ::isEmailTaken()

---

.gitignore
README.md
auth.class.php
database.sql
languages/en_GB.php

`isBlocked()` attempts now on rolling time. (For better UX)
`isBlocked()` now public and can require CAPTCHA verification. (For better UX)
Added settings for attack mitigation.
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/Conver%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6231022%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/99%23issuecomment-139883604%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-09-13T14%3A48%3A35Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6231022%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22h …

Advanced Attack Mitigation

---

languages/it_IT.php

italian language file

---

config.class.php

ability to override config setting from user code without permanently setting database.
<a href='https://www.codereviewhub.com/PHPAuth/PHPAuth/pull/116?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/PHPAuth/PHPAuth/pull/116'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

feature: config override method

---

auth.class.php

rewritten send mail option
renamed `$suppressed` varname to a more clearer naming `$sendmail`
added manual control to send mail 
removed language overwrite and set text result from correponding methods
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/PHPAuth/PHPAuth/pull/122%23issuecomment-142905643%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/122%23issuecomment-142905643%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22I%20have%20a%20question%20about%20the%20mail%20suppression%3A%20if%20we%20set%20%24sendmail%20%3D%20false%20the%20activation%20is%20still%20working%3B%20how%20can%20the%20user%20activate%20his%20account%20without%20the%20generated%20key%3F% …

rewritten  Christin Milloy suppression email

---

README.md

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/PHPAuth/PHPAuth/pull/131%23issuecomment-145400831%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/131%23issuecomment-145401951%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/131%23issuecomment-145406320%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/131%23issuecomment-145400831%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22I%20would%20not%20do%20this%20until%20we%20have%20some%20actual%20tests%20running%2C%20but%20it%20needs%20to%20be%20done.%20%22%2C%20%22created_at%22%3A%20%222015-10-04T23%3A23%3A19Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5 …

added travis validation check

---

phpunit.xml

now i hope it work
<a href='https://www.codereviewhub.com/PHPAuth/PHPAuth/pull/130?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/PHPAuth/PHPAuth/pull/130'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

missing file for travis

---

.travis.yml

found it ! :)
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/PHPAuth/PHPAuth/pull/129%23issuecomment-145400469%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/129%23issuecomment-145400573%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/129%23issuecomment-145400894%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/129%23issuecomment-145401276%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/129%23issuecomment-145402367%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/129%23issuecomment-145400469%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22The%20biggest%20problem%20is%20to%20create%20a%20database%20and%20push%20info%20into%20it%2C%20so%20 …

fixed travis problem

---

Auth.php
Config.php
languages/de_DE.php

This allows extending classes to overwrite functions and variables and is way better OOP coding style.

Changed visibility of functions and variables from "private" to "protected"

---

languages/cs_CZ.php

This file contains Czech (cs_CZ) localization in non-BOM UTF-8 encoding.

Czech localization for the project

---

languages/vi_VN.php

Hi there, I just added Vietnamese translation file in languages folder.

Added Vietnamese translation file in languages folder

---

Auth.php
database_informix.sql

rowCount not recommended for checking sql select results
These changes add informix compatibility

Removing rowCount for sql select results. Adding a sql file for informix

---

languages/ps_AF.php

I have create a Pashto (Afghanistan language) translation file please add it.
Thanks,
Muhammad Nasir Rahimi

Add Pashto translation by Muhammad Nasir Rahimi

---

languages/pt_BR.php

Translated _['password_weak']_ and fixed some others

update pt_BR language

---

languages/sr_RS.php

Serbian language added as "sr_RS"

serbian language added

---

languages/id_ID.php

add some words I have forgotten

Indonesia language added.(add some words)

---

languages/hu_HU

Hungarian translation added

---

Auth.php

We already disallow 2 users having the same email in register(), the same should be enforced in changeEmail().

Check if email is already taken in changeEmail()

---

Auth.php

Revert "Make current password parameter mandatory for changePassword"

---

Auth.php

The resetPass function does not check the strength of the password before resetting the password.

Added a password strength check to resetPass

---

Auth.php
README.md
database_mssql.sql
database_mysql.sql
database_pgsql.sql

This will add SMTP debugging feature to PHPAuth, very useful if you are having email/smtp issues.

Add SMTP debugging feature

---

languages/ru_RU.php
languages/uk_UA.php

This PR corrects bad translation in russian and ukrainian translations.

Fixed incorrect translations

---

Auth.php
Config.php
README.md
composer.json
database_defs/database_informix.sql
database_defs/database_mssql.sql
database_defs/database_mysql.sql
database_defs/database_pgsql.sql

**Database:**
- rkey renamed to token
- Increased max size of password field to 255 (for future crypt algos)
- added recaptcha definition
**Auth.php**
-  rkey changed to token
- fixed magic access to translated messages
- optimised getIP method
- added recaptcha config
- renamed some arguments
- added reCaptcha check method (not used now)
- exploded some PDO requests to named placeholders
- optimzed some methods
- rolled back method getUser: added arg '$with_password = false'
- added method updateUser()
- added method getCurrentUID()
**Config:**
- added recaptcha agrs
- critical fixes (translate engine fixed)
- added custom config fields
**Composer:**
- added dependancy ' google/recaptcha'
**Readme:** 
- updated documentation

Custom config options, optimization, critical fixes

---

Auth.php
Config.php
database_defs/database_informix.sql
database_defs/database_mssql.sql
database_defs/database_mysql.sql
database_defs/database_pgsql.sql

Removed deprected code, optimisation DB, opt. code

Removed deprected code, optimisation DB, opt. code

---

languages/de_DE.php

https://github.com/PHPAuth/PHPAuth/issues/323

Added 'account_not_found' key + translation in languages/de_DE

---

README.md
languages/sl_SI.php

Fix and update Slovenian translation.

Fix Slovenian translation

---

Auth.php
Config.php
README.md
database_defs/database_informix.sql
database_defs/database_mssql.sql
database_defs/database_mysql.sql
database_defs/database_pgsql.sql
tests/AuthTest.php

As discussed in #326.
Added a unit test which passes.
I set the default to `false`, which is the current behavior.

Add configuration option to allow multiple sessions for one user

---

Auth.php
README.md
composer.json

Issue #317 - Make PHP 7.0+ minimum requirement

---

README.md

https://help.waffle.io/waffle-shutdown/waffle-shutdown-tldr

Remove Waffle Badge

---

Auth.php

updateUser(): unset uid which is set in getUser(). array generated in getUser() is now usable as parameter for updateUser()

updateUser() unset uid

---

Auth.php

I change the return value in phpdoc and added the ID to the array.

BUGFIX: fix phpdoc and return the inserted userid #373

---

Auth.php

_My suggestion:_ The function `addRequest()` will return the token and expiration date. `requestReset()` will return this too.
@Conver Is this change acceptable?

CHANGE: token and expiration time added #386

---

languages/de_DE.php

CHANGE: typo in german translation #436

---

Auth.php

Fix phpdoc
(Do we need a issue?)

CHANGE: fix phpdoc return value

---

Config.php

[BUGFIX] Check configuration pdo query #455

---

languages/zh_CN.php
languages/zh_TW.php

A brief translation, and if there is any unsuitable place for later use, make specific adjustments. Others are welcome to make a better text explanation PR.

Simplified Chinese & Traditional Chinese

---

.gitignore
Auth.php
Config.php
composer.json
tests/AuthTest.php

Code formatting and modification of code test database information

Code formatting and modification of code test database information

---

Auth.php

I need the user id, because i send the email on my own and i need more information about the user (e. g. fullname).

return user-id on requestReset()

---

Auth.php

In case we want to manage mail in our solution we have to get token in order to send mail with activation link or reset link.
This need to be used with these parameters:
emailmessage_suppress_activation = 1
emailmessage_suppress_reset = 1

return token on all function that can send an email.

---

languages/id_ID.php

- Added comma punctuation.
- Translate the word "Hello".
- Improvements to the "di" conjunction

update lang id_ID

---

Auth.php
Config.php
LICENSE
README.md
composer.json
tests/AuthTest.php

Add PHP 7 type hints, make some general code changes and "fix" #481 
**Important** I added a phpauth version into composer.json for future updates!

PHP 7 improvements

---

Auth.php
files/import_langs_to_sql.php
languages/en_GB.php

Not tested, it seems there is no problem writing this way.
If you think you can join, please test and then merge.

Add the translation field required by the php version

---

Auth.php
languages/en_GB.php

Better use of translation tools, modification of wording and modification of translation fields
@KarelWintersky 
https://github.com/PHPAuth/PHPAuth/pull/486#issuecomment-771623847

Better use of translation tools

---

Auth.php
README.md
database_defs/database_informix.sql
database_defs/database_mssql.sql
database_defs/database_mysql.sql
database_defs/database_pgsql.sql

Updated the way the cookie is set so we have an option for the same site cookie as well. Then added in option for samesite cookie and defaulted it to Lax. Which is what most browser default to anyway.

Added in option to modify same site cookie preferences

---

Auth.php

clear cookie on logout

---

sources/Helpers.php

Show Error:
```html
Undefined class constant 'self::TOKEN_LENGTH' 
```

FIX `Undefined class constant 'self::TOKEN_LENGTH'`
